### ISSUE TITLE
missing Kora-light Pop!_Shop icon

### ISSUE THREAD

**Issue by vinayakumarMurganoor** [bikass/kora#113]
the kora-light is missing pop!_shop icon.
![image](https://user-images.githubusercontent.com/8676836/125240738-c9280580-e2ea-11eb-8fd4-7778a8d863e0.png)

**Comment by bikass** [comment]
Fixed it. You can check if it works from latest commit.

**Comment by vinayakumarMurganoor** [comment]
problem still persists.
After getting the latest commit, I copied all theme folders to ~/.icons .

```
~/xyz/kora ‹master› 
╰─$ cp -r kora* ~/.icons
```
used the tweaks app to apply the new icons.

**Comment by bikass** [comment]
You can update icon theme cache, or try downloading again.

**Comment by vinayakumarMurganoor** [comment]
perfect, with 
1. sudo update-icon-caches ~/.icons/*
2. and restarting the gnome-shell worked
For new installer there shall be no problem.
